name: Run
#on: 
 # watch:
 #   types: started
 # schedule:
 # - cron: '0 */1 * * *'
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3.1.0
        
      - name: chmod
        working-directory: ${{ github.workspace }}
        run: |
            sudo chmod -R 777 .

      - name: Setup Python environment
        uses: actions/setup-python@v4.5.0
        
      - name: start
        working-directory: ${{ github.workspace }}
        run: |
            python main.py
