name: Clean Workflows Action
on: 
  schedule:
    - cron: '0 8 * * *'
jobs:
  clean:
    name: clean
    runs-on: ubuntu-latest
    steps:
      - name: Clean Workflow Action
        uses: igorjs/gh-actions-clean-workflow@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days_old: 1
